name: stat214
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - joblib
  - tqdm
  - pip
  - pip:
      - matplotlib-inline
      - jupyterlab